source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gemspec

gem 'combustion', '~> 1.3'
gem 'debug', '>= 1.7.2'
gem 'rails', '~> 7.0'
gem 'rspec', '>= 3.12.0'
gem 'rspec-rails', '~> 5.1'
gem 'rubocop-rails', '~> 2.11', '>= 2.11.1'
gem 'rubocop-rspec', '~> 2.1', '>= 2.1.0'
