begin
  require 'bundler/setup'
rescue LoadError
  puts 'Run bundle install to run rake tasks'
end

require 'rails'
require 'combustion'

Bundler.require :default, Rails.env
Combustion.path = 'spec/dummy'
Combustion::Application.configure_for_combustion

APP_RAKEFILE = File.expand_path('spec/dummy/Rakefile', __dir__)
load 'rails/tasks/engine.rake'

load 'rails/tasks/statistics.rake'

require 'bundler/gem_tasks'

Combustion::Application.load_tasks
