# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"
gem 'actionpack'
gem 'activerecord'
gem 'combustion'
gem 'componeer', path: '../../'
gem 'sprockets'
gem 'sprockets-rails'
gem 'tailwindcss-rails', '~> 2.0'
